
site_name: Comp 105 online interpreter documentation

docs_dir: docs

nav:
  - Home: index.md
  - About: about.md
  - 'Student user guide':
    - Tutorial: user/tutorial.md
    - 'API Reference': user/api.md
  - 'Developer corner':
    - Design: dev/design.md

theme: readthedocs

