version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Workaround for Puppeteer on Docker
          command: 'sh .circleci/puppeteer.sh'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Generate production build
          command: npm run compile
      - run:
          name: Test builds
          command: npm test

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Compile to production
          command: npm run build
      - run:
          name: Add deployment key to known_hosts
          command: ssh-keyscan -H $DEPLOYMENT_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy code to server
          command: scp -r ./build/* $DEPLOYMENT_USER@$DEPLOYMENT_HOST:$DEPLOYMENT_DIR

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
              branches:
                only: master
